# Generated by Django 5.1.1 on 2024-10-03 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='voucher',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
